### ISSUE TITLE
Mojibake in generated .fbx.meta file

### ISSUE THREAD

**Issue by xantoz-vrc** [HashEdits/Face-Tracking-Patcher#7]
I used the patcher as included in a FT addon package for an Avatar. However it seems like it created an .fbx.meta file with a broken GUID. Any idea how this could happen? How is the accompanying .fbx.meta file created typically? I would've assumed it is simply created without dependency on any of the files being patched, or could it be somehow confused due to some discrepancies in my project? For the record my project was not created clean, but rather it was created from an old version of the avatar package and then upgraded to the version needed for the FT addon, which might cause issues, but I wouldn't expect this particular issue, and the .fbx file itself patched perfectly fine. 

As for my project itself I was able to workaround the issue by manually fixing the broken GUID.

Sorry for the lack of information to reproduce etc. I will respond to requests for information you might need to further debug this.

![UflnSOAa](https://github.com/user-attachments/assets/1459e0c0-e7d9-40f8-885f-fa0e31a374e9)

**Comment by HashEdits** [comment]
Hey, my clue is that you might've had a version with the import settings altered leading to the patch of the fbx going alright but not .meta file.

I've reached out to the creator of that Add-on and he replied the following:

`hey, I just tried the add-on again and everything works just fine, apparently that person had the issue because their project was made with the version 1.1 of Haishima and THEN they updated the files with haishima 1.2, the problem with that is, I can't try it bc the version 1.1 of the avatar is not available to download anymore, only the latest one`

Can you confirm that it's the avatar it doesn't have to do with the tool but the avatar itself?

**Comment by HashEdits** [comment]
Hey, Chatted with the creator and he told me he took care of the issue,
This doesn't have anything to do with the tool but rather a version missmatch only on the import file.

Please contact the add-on creator if you need any further support.

Thank you
